const mongoose = require('mongoose')

const PatientSchema = new mongoose.Schema({
    name: String,
    phone: String,
    email: String,
    address: String,
    age: String,
    gender: String,

    runningnose: String,
    sneeze: String,
    cough: String,
    wheeze: String,
    headache: String,
    itch: String,
    swell: String,
    redrashes: String,
    familyhistory: String,

    banana: String,
    mango: String,
    fruit1: String,
    fruit2: String,
    lime: String,

    avaraikai: String,
    beans: String,
    beetroot: String,
    brinjal: String,
    cabbage: String,
    capsicum: String,
    cauliflower: String,
    carrot: String,
    chowchow: String,
    corn: String,
    cucumber: String,
    drumstick: String,
    greens: String,
    gourds: String,
    kovaikai: String,
    kothavarai: String,
    lfinger: String,
    malli: String,
    mushroom: String,
    nuckol: String,
    onion: String,
    peas: String,
    potroot: String,
    potato: String,
    pumkin: String,
    pudina: String,
    radish: String,
    tomato: String,
    tondaikai: String,
    vazpoo: String,
    yams: String,

})

mongoose.model("patient", PatientSchema)